### ISSUE TITLE
[3.0.5] UNIVERSALENCHANTS_FLAME already exists in enum class net.minecraft.class_1886

### ISSUE THREAD

**Issue by Desempregago** [Fuzss/universalenchants-fabric#2]
![image](https://user-images.githubusercontent.com/14002834/161342564-44a15c79-e8fe-4b0d-a1c7-7bd6f37cb172.png)

**Comment by Desempregago** [comment]
[Full Crash Report](https://pastebin.com/UJqzGMUk)

**Comment by Fuzss** [comment]
Does this happen every time?

**Comment by Desempregago** [comment]
No, only in worlds created with the same name after the old one is deleted.
but this only happens if I delete the world and create another without exiting the game

**Comment by Fuzss** [comment]
Does it always happen then though? I tried a few times and never got a crash once.

**Comment by Desempregago** [comment]
Could be an isolated case... I'll close the issue and if I manage to reproduce it I'll reopen and explain how it happened

**Comment by Fuzss** [comment]
Should be more stable in v3.0.6 now.
